name: Check Boot Image Format

on:
  workflow_dispatch:

jobs:
  unpack-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Download boot.img
        run: curl -fsSL "https://sourceforge.net/projects/plato-evox/files/EvolutionX-16.0-20260514-plato-11.7-Unofficial/boot.img/download" -o boot.img

      - name: Run script
        run: |
          cat << 'EOF' > check_boot.sh
          #!/bin/bash
          
          err() {
              echo "[ERROR] $*" >&2
              [ -n "${temp:-}" ] && rm -rf "$temp"
              exit 1
          }
          
          check_cmd() {
              command -v "$1" &>/dev/null
          }
          
          install_magiskboot() {
              local magiskboot_url dest
              magiskboot_url="https://github.com/nand-o/magiskboot-prebuilt/raw/main/linux_x86_64/magiskboot"
              dest="/usr/local/bin/magiskboot"
          
              sudo curl -fsSL "$magiskboot_url" -o "$dest"
              sudo chmod 755 "$dest"
          }
          
          if ! check_cmd "magiskboot"; then
              install_magiskboot
          fi
          
          boot_path=$(realpath "$1")
          if [ -z "${boot_path:-}" ]; then
              err "boot.img required."
          elif [ ! -f "$boot_path" ]; then
              err "File '$boot_path' doesn't exist."
          fi
          
          temp=$(mktemp -d)
          pushd "$temp" >/dev/null || err "pushd failed"
          
          dst="$temp/$(basename "$boot_path")"
          cp "$boot_path" "$dst"
          boot_path="$dst"
          
          output=$(magiskboot unpack "$boot_path" 2>&1)
          rc=$?
          
          if [ "$rc" -ne 0 ]; then
              err "Failed to unpack boot image"
          fi
          
          kernel_fmt=$(echo "$output" | grep 'KERNEL_FMT' | awk '{print $2}' | cut -f2 -d '[' | cut -f1 -d ']')
          
          echo "Your kernel format is $kernel_fmt"
          
          popd >/dev/null || err "popd failed"
          rm -rf "$temp"
          exit 0
          EOF
          
          chmod +x check_boot.sh
          ./check_boot.sh boot.img > output.txt
          cat output.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-format-output
          path: output.txt
